### ISSUE TITLE
编译linux headers

### ISSUE THREAD

**Issue by AyFun** [AyFun/HiSTBLinux_drive#2]
@GreenTeodoro839
前4步编译出来的内核可以当headers用，如果只要headers也可以第4步加个headers_install。
然后移动到对应/usr/src/linux-headers-xx的目录，或者在编译驱动时指定headers目录

**Comment by GreenTeodoro839** [comment]
能详细说一下怎么弄吗？第三步拿到.config文件是干什么用的？第四步我把source文件夹复制到设备，make提示路径不对，复制的位置还有要求吗

**Comment by AyFun** [comment]
@GreenTeodoro839 .config是编译内核的配置文件，设备不一样配置不一样。路径一般没啥要求，具体提示可以贴出来看看。

**Comment by GreenTeodoro839** [comment]
> @GreenTeodoro839 .config是编译内核的配置文件，设备不一样配置不一样。路径一般没啥要求，具体提示可以贴出来看看。

我用电脑make linux那一步就一直出错
``make[1]: Entering directory '/root/HiSTBLinuxV100R005C00SPC050/source/kernel'
make[2]: Entering directory '/root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y'
make[3]: Entering directory '/root/HiSTBLinuxV100R005C00SPC050/out/hi3798mv100/hi3798mdmo1a/obj/source/kernel/linux-4.4.y'
  GEN     ./Makefile
#
# configuration written to .config
#
make[3]: Leaving directory '/root/HiSTBLinuxV100R005C00SPC050/out/hi3798mv100/hi3798mdmo1a/obj/source/kernel/linux-4.4.y'
make[2]: Leaving directory '/root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y'
make pcie_config
make[2]: Entering directory '/root/HiSTBLinuxV100R005C00SPC050/source/kernel'
make[2]: Nothing to be done for 'pcie_config'.
make[2]: Leaving directory '/root/HiSTBLinuxV100R005C00SPC050/source/kernel'
make[2]: Entering directory '/root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y'
make[3]: Entering directory '/root/HiSTBLinuxV100R005C00SPC050/out/hi3798mv100/hi3798mdmo1a/obj/source/kernel/linux-4.4.y'
  GEN     ./Makefile
scripts/kconfig/conf  --oldconfig Kconfig
#
# configuration written to .config
#
make[3]: Leaving directory '/root/HiSTBLinuxV100R005C00SPC050/out/hi3798mv100/hi3798mdmo1a/obj/source/kernel/linux-4.4.y'
make[2]: Leaving directory '/root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y'
make -C /root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y ARCH=arm \
        CROSS_COMPILE=arm-histbv310-linux- \
        O=/root/HiSTBLinuxV100R005C00SPC050/out/hi3798mv100/hi3798mdmo1a/obj/source/kernel/linux-4.4.y \
        CONFIG_MSP=y \
        HI_CONFIG_WIFI= \
        HI_CONFIG_BLUETOOTH= \
        CONFIG_ADVCA= \
         \
        CFLAGS_KERNEL= AFLAGS_KERNEL= uImage modules
make[2]: Entering directory '/root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y'
make[3]: Entering directory '/root/HiSTBLinuxV100R005C00SPC050/out/hi3798mv100/hi3798mdmo1a/obj/source/kernel/linux-4.4.y'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  Using /root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y as source for kernel
  /root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y is not clean, please run 'make mrproper'
  in the '/root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y' directory.
make[3]: *** [/root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y/Makefile:987: prepare3] Error 1
make[3]: Leaving directory '/root/HiSTBLinuxV100R005C00SPC050/out/hi3798mv100/hi3798mdmo1a/obj/source/kernel/linux-4.4.y'
make[2]: *** [Makefile:150: sub-make] Error 2
make[2]: Leaving directory '/root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y'
make[1]: *** [Makefile:184: /root/HiSTBLinuxV100R005C00SPC050/out/hi3798mv100/hi3798mdmo1a/obj/source/kernel/linux-4.4.y/arch/arm/boot/uImage] Error 2
make[1]: Leaving directory '/root/HiSTBLinuxV100R005C00SPC050/source/kernel'
make: *** [Makefile:154: linux] Error 2

 #### make target "linux" failed !!!(3 seconds) ####
``

**Comment by AyFun** [comment]
@GreenTeodoro839 在电脑上交叉编译吗？交叉编译可以参考 #1 和https://bbs.histb.com/d/1286-zai-windowsxia-bian-yi-hai-si-linuxgu-jian
能不能成功不好说，建议在设备上编译。

**Comment by GreenTeodoro839** [comment]
> @GreenTeodoro839 在电脑上交叉编译吗？交叉编译可以参考 #1 和https://bbs.histb.com/d/1286-zai-windowsxia-bian-yi-hai-si-linuxgu-jian 能不能成功不好说，建议在设备上编译。

不是交叉编译，第四步之前make linux报错

**Comment by AyFun** [comment]
@GreenTeodoro839 可能是编译目录不干净，删了重来试试，然后第三步的配置可以参考https://github.com/JasonFreeLab/HiSTBLinuxV100R005C00SPC050
的说明

**Comment by GreenTeodoro839** [comment]
> @GreenTeodoro839 可能是编译目录不干净，删了重来试试，然后第三步的配置可以参考https://github.com/JasonFreeLab/HiSTBLinuxV100R005C00SPC050 的说明

我在电脑编译后，按照你说的把source文件夹复制到设备，然后make headers_install就报错
root@hi3798mv100:/mnt/sda1/linux-4.4.y# make headers_install
make[1]: *** /root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y: No such file or directory.  Stop.
make: *** [Makefile:24: __sub-make] Error 2
把整个目录都复制到设备，make -C 目录编译驱动还是报错
make: Entering directory '/root/HiSTBLinuxV100R005C00SPC050/out/hi3798mv100/hi3798mdmo1a/obj/source/kernel/linux-4.4.y'
/root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y/Makefile:670: Cannot use CONFIG_CC_STACKPROTECTOR_REGULAR: -fstack-protector not supported by compiler  CHK     include/config/kernel.release
  Using /root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y as source for kernel
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[3]: 'include/generated/mach-types.h' is up to date.
  CC      kernel/bounds.s
gcc: error: unrecognized argument in option ‘-mabi=aapcs-linux’
gcc: note: valid arguments to ‘-mabi=’ are: ms sysv
gcc: error: unrecognized command line option ‘-mlittle-endian’
gcc: error: unrecognized command line option ‘-mapcs’
gcc: error: unrecognized command line option ‘-mno-sched-prolog’
gcc: error: unrecognized command line option ‘-mno-thumb-interwork’
gcc: error: unrecognized command line option ‘-mfpu=vfp’
make[3]: *** [/root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y/./Kbuild:45: kernel/bounds.s] Error 1
make[2]: *** [/root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y/Makefile:1004: prepare0] Error 2
make[1]: *** [Makefile:150: sub-make] Error 2
make: *** [Makefile:24: __sub-make] Error 2
make: Leaving directory '/root/HiSTBLinuxV100R005C00SPC050/out/hi3798mv100/hi3798mdmo1a/obj/source/kernel/linux-4.4.y'
大佬能不能给mv100编译一个header？内核是4.4.35_ecoo_16010066，想安装rtl8192eu驱动

**Comment by AyFun** [comment]
> > @GreenTeodoro839 可能是编译目录不干净，删了重来试试，然后第三步的配置可以参考https://github.com/JasonFreeLab/HiSTBLinuxV100R005C00SPC050 的说明
> 
> 我在电脑编译后，按照你说的把source文件夹复制到设备，然后make headers_install就报错 root@hi3798mv100:/mnt/sda1/linux-4.4.y# make headers_install make[1]: *** /root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y: No such file or directory. Stop. make: *** [Makefile:24: __sub-make] Error 2 把整个目录都复制到设备，make -C 目录编译驱动还是报错 make: Entering directory '/root/HiSTBLinuxV100R005C00SPC050/out/hi3798mv100/hi3798mdmo1a/obj/source/kernel/linux-4.4.y' /root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y/Makefile:670: Cannot use CONFIG_CC_STACKPROTECTOR_REGULAR: -fstack-protector not supported by compiler CHK include/config/kernel.release Using /root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y as source for kernel GEN ./Makefile CHK include/generated/uapi/linux/version.h CHK include/generated/utsrelease.h make[3]: 'include/generated/mach-types.h' is up to date. CC kernel/bounds.s gcc: error: unrecognized argument in option ‘-mabi=aapcs-linux’ gcc: note: valid arguments to ‘-mabi=’ are: ms sysv gcc: error: unrecognized command line option ‘-mlittle-endian’ gcc: error: unrecognized command line option ‘-mapcs’ gcc: error: unrecognized command line option ‘-mno-sched-prolog’ gcc: error: unrecognized command line option ‘-mno-thumb-interwork’ gcc: error: unrecognized command line option ‘-mfpu=vfp’ make[3]: *** [/root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y/./Kbuild:45: kernel/bounds.s] Error 1 make[2]: *** [/root/HiSTBLinuxV100R005C00SPC050/source/kernel/linux-4.4.y/Makefile:1004: prepare0] Error 2 make[1]: *** [Makefile:150: sub-make] Error 2 make: *** [Makefile:24: __sub-make] Error 2 make: Leaving directory '/root/HiSTBLinuxV100R005C00SPC050/out/hi3798mv100/hi3798mdmo1a/obj/source/kernel/linux-4.4.y' 大佬能不能给mv100编译一个header？内核是4.4.35_ecoo_16010066，想安装rtl8192eu驱动

首先我没有make headers_install这一步，然后看你在A目录输入，B目录报错，感觉你的环境乱了。
我没有你的设备，所以也办法帮你编译好，建议想简单点还是找神雕大佬付费吧。
