### ISSUE TITLE
请教 Invalid module format 是什么原因

### ISSUE THREAD

**Issue by blutterz** [AyFun/HiSTBLinux_drive#3]
按照您的教程可以成功编译出 ko 文件。 但是 insmod 会报错误
是我有什么地方做的不对吗
[638704](insmod: ERROR: could not insert module rtl8188fu.ko: Invalid module format)

**Comment by AyFun** [comment]
@blutterz 可能是第二步的vermagic.h 和设备内核版本不一致，dmesg看看日志

**Comment by blutterz** [comment]
十分感谢 。如您所说，现在不报错了，但是挂载驱动后卡死。

**Comment by AyFun** [comment]
@blutterz 卡死可能是驱动版本问题，要么试试文件自带的，要么驱动官网上找找
